/**
 * This is auto-generated file, don't modify this file manually
 */

// groups_fields
export enum GroupsFields {
  MARKET = 'market',
  MEMBER_STATUS = 'member_status',
  IS_FAVORITE = 'is_favorite',
  IS_SUBSCRIBED = 'is_subscribed',
  IS_SUBSCRIBED_PODCASTS = 'is_subscribed_podcasts',
  CAN_SUBSCRIBE_PODCASTS = 'can_subscribe_podcasts',
  CITY = 'city',
  COUNTRY = 'country',
  VERIFIED = 'verified',
  DESCRIPTION = 'description',
  WIKI_PAGE = 'wiki_page',
  MEMBERS_COUNT = 'members_count',
  REQUESTS_COUNT = 'requests_count',
  COUNTERS = 'counters',
  COVER = 'cover',
  CAN_POST = 'can_post',
  CAN_SUGGEST = 'can_suggest',
  CAN_UPLOAD_STORY = 'can_upload_story',
  CAN_UPLOAD_DOC = 'can_upload_doc',
  CAN_UPLOAD_VIDEO = 'can_upload_video',
  CAN_UPLOAD_CLIP = 'can_upload_clip',
  CAN_SEE_ALL_POSTS = 'can_see_all_posts',
  CAN_CREATE_TOPIC = 'can_create_topic',
  ACTIVITY = 'activity',
  FIXED_POST = 'fixed_post',
  HAS_PHOTO = 'has_photo',
  STATUS = 'status',
  MAIN_ALBUM_ID = 'main_album_id',
  LINKS = 'links',
  CONTACTS = 'contacts',
  SITE = 'site',
  MAIN_SECTION = 'main_section',
  SECONDARY_SECTION = 'secondary_section',
  WALL = 'wall',
  TRENDING = 'trending',
  CAN_MESSAGE = 'can_message',
  IS_MARKET_CART_ENABLED = 'is_market_cart_enabled',
  IS_MESSAGES_BLOCKED = 'is_messages_blocked',
  CAN_SEND_NOTIFY = 'can_send_notify',
  HAS_GROUP_CHANNEL = 'has_group_channel',
  GROUP_CHANNEL = 'group_channel',
  ONLINE_STATUS = 'online_status',
  START_DATE = 'start_date',
  FINISH_DATE = 'finish_date',
  AGE_LIMITS = 'age_limits',
  BAN_INFO = 'ban_info',
  ACTION_BUTTON = 'action_button',
  AUTHOR_ID = 'author_id',
  PHONE = 'phone',
  HAS_MARKET_APP = 'has_market_app',
  ADDRESSES = 'addresses',
  LIVE_COVERS = 'live_covers',
  IS_ADULT = 'is_adult',
  CAN_SUBSCRIBE_POSTS = 'can_subscribe_posts',
  WARNING_NOTIFICATION = 'warning_notification',
  MSG_PUSH_ALLOWED = 'msg_push_allowed',
  STORIES_ARCHIVE_COUNT = 'stories_archive_count',
  VIDEO_LIVE_LEVEL = 'video_live_level',
  VIDEO_LIVE_COUNT = 'video_live_count',
  CLIPS_COUNT = 'clips_count',
  IS_BUSINESS = 'is_business',
  TEXTLIVES_COUNT = 'textlives_count',
}
